name: Sign BrickUp Shortcut

on:
  workflow_dispatch:

jobs:
  sign:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Sign Shortcut
        run: |
          shortcuts sign \
            --mode anyone \
            --input BrickUp.shortcut \
            --output BrickUp_SIGNED.shortcut

      - name: Upload signed shortcut
        uses: actions/upload-artifact@v4
        with:
          name: BrickUp_SIGNED
          path: BrickUp_SIGNED.shortcut
